11449: 5  # Elixir of Agility
3188: 5   # Elixir of Ogre Strength
8951: 5   # Elixir of Greater Defense
17708: 5  # Elixir of Frost Power
6373: 5   # Elixir of Firepower
3825: 5   # Elixir of Fortitude